os: linux
dist: xenial
language: node_js
node_js: lts/dubnium
install: yarn
jobs:
  include:
    - stage: test
      script:
        - yarn test:ci
        - npx codechecks
    -
      script:
        - yarn coverage:ci
